### ISSUE TITLE
Monitor failover

### ISSUE THREAD

**Issue by nikoladsp** [citusdata/pg_auto_failover#130]
Hi,
I have one question: as monitor node is single point of failure -is it possible that it fail-over automatically alongside DB instance? Or if not - what would be the best way to do so?

Thank you kindly.

Best regards

**Comment by bwalendz** [comment]
I am also wondering about this?

**Comment by nikoladsp** [comment]
I eventually gave up and used keepalived to drive the 'cluster' of 2 PGs and make scripts called to promote PG on master and demote PG on backup

**Comment by vavdoshka** [comment]
Indeed it is a very interesting point.
As per me, It defeats the whole point of HA setup.

**Comment by vavdoshka** [comment]
from what I understood this issue would be resolved by this https://github.com/citusdata/pg_auto_failover/pull/59

Also found interesting article about the roadmap of this project -
http://thewindowsupdate.com/2019/10/17/auto-failover-with-postgresql-12/

**Comment by DimCitus** [comment]
Hi @nikoladsp, @bwalendz, @vavdoshka. The monitor being a SPOF in pg_auto_failover architecture is a known weakness of the current solution. Our plan is to provide disaster recovery facilities for the monitor, in two ways:
  1. first, make it possible to introduce a monitor without the state of the cluster, and fill the state from the nodes in the formations ; there are some traps when doing that, that's why it's not there yet
  2. second, integration archiving and PITR for the monitor right into pg_auto_failover. You can already implement that with pgBackRest or other recovery software for Postgres.

When thinking about that topic, one needs to remember that Postgres streaming replication does not need the monitor. When the monitor is not available, the only operation that is prevented is a failover. In other words, pg_auto_failover architecture and design tolerates the unavailability of any ONE node.
