### ISSUE TITLE
Hard to setup when having external requirements (pg_hba.conf / listen_addresses / no trust...)

### ISSUE THREAD

**Issue by Markus-** [citusdata/pg_auto_failover#165]
Hi,

I am not allowed due to several security requirements to use the quite "open" base-configuration.

So I tried to adjust several things, but right now I have some open issues:

I started with the monitor:
I need to have only md5/scam entries for users not equal postgres, so I tried to create a .pgpass-file for autoctl_node (pg_auto_failover / template1) and adjusting the pg_autoctl.cfg to "host=localhost". 

pg_autoctl insists to connect to template1 with [local]. Is there any other place where to adjust the access? 

Also: How to stop / restart the monitor? pg_autoctl doesn't seem to have such an option.

Regards
Markus

**Comment by Markus-** [comment]
Should

pg_autoctl show events use the same connection like pg_autoctl run?

When I use show events it uses [local] - when I use run it seems to use 127.0.0.1 as configured.

**Comment by DimCitus** [comment]
With release 1.2 you can choose `--auth md5` or other authentication mechanisms, and setup SSL connections everywhere as covered in the new documentation page at https://pg-auto-failover.readthedocs.io/en/latest/security.html.

Moreover, you can also use `--skip-pg-hba` so that you may install your own HBA rules without seeing any edits by pg_auto_failover, just manage your provisioning as usual.

The connection to the local Postgres instance is driven by `--pghost` and defaults to using Unix  Sockets.

You can restart the monitor database with the usual Postgres commands, see #206 where we integrate the Postgres management with the pg_autoctl process management, that might land in release 1.4 later.

**Comment by DimCitus** [comment]
I believe it should now be possible for you @Markus- to be compliant with the security policy you need to deploy. Please have a look at https://pg-auto-failover.readthedocs.io/en/latest/security.html to assess and deploy. If you need to, of course you may open this issue again with more information.
