### ISSUE TITLE
choose node manually

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [citusdata/pg_auto_failover#23]
Is it possible to manually choose the node that will become primary or wait_primary?
thanks

**Comment by dimitri** [comment]
Hi @ROBERT-MCDOWELL, yes it's possible. I can think of two ways to achieve what you ask:

  1. Initialize a PostgreSQL instance manually before registering the node, using `pg_ctl initdb` (or `initdb`, it's the same thing), and the `pg_autoctl create Postgres` with the same PGDATA. You need to make sure you register this node first in its group of course.

  2. The first node that registers to a group is always going to be the primary, so just make sure your candidate for being a primary registers first to the monitor.

The first way to do it will error out when things are not as expected, because `pg_autoctl create postgres` does not know how to initialise a standby from an existing PGDATA.

Lastly, it needs to be said: when using pg_auto_failover the role of your Postgres instance will change from primary to secondary in an automated fashion. That means without manual intervention. This means that your setup must continue working when the secondary has been promoted to be a primary. Given that, is it so important to elect which node is going to be a primary initially?

**Comment by ROBERT-MCDOWELL** [comment]
thanks for your answer
>  is it so important to elect which node is going to be a primary initially?
yes it is, as I'm developing since years a massive bash script that manages nodes in a geocluster so when the master is down it selects from its list by order. so once the new master node is selected obviously postgresql of this node must be master too. For now I uses what's existing already but it's a little tedious.

**Comment by ROBERT-MCDOWELL** [comment]
thanks for your answer

-  is it so important to elect which node is going to be a primary initially?
yes it is, as I'm developing since years a massive bash script that manages nodes in a geocluster so when the master is down it selects from its list by order. so once the new master node is selected obviously postgresql of this node must be master too. For now I uses what's existing already but it's a little tedious.

**Comment by DimCitus** [comment]
See https://pg-auto-failover.readthedocs.io/en/latest/how-to.html#manual-failover-switchover-and-promotions and the command `pg_autoctl perform promotion` that allows choosing which node is promoted.
