### ISSUE TITLE
"ERROR:  permission denied for table node" using failover command

### ISSUE THREAD

**Issue by Wolfsrudel** [citusdata/pg_auto_failover#25]
```
psql postgres://autoctl_node@monitor/pg_auto_failover
psql (11.3 (Ubuntu 11.3-1.pgdg18.04+1))
Type "help" for help.

pg_auto_failover=> select pgautofailover.perform_failover(formation_id => 'default', group_id => 0);
ERROR:  permission denied for table node
CONTEXT:  SQL statement "UPDATE pgautofailover.node SET goalstate = $1, statechangetime = now() WHERE nodename = $2 AND nodeport = $3"
pg_auto_failover=>
```

**Comment by DimCitus** [comment]
Hi @Wolfsrudel, thanks for the feedback.

The user `autoctl_node` has just enough privileges to be used from a node running the `pg_autoctl` tool. This does not include triggering a manual failover. 

To use the `perform_failover` API you need to log-in to the monitor as the database owner role: `autoctl`. The creation steps of the database cluster for the monitor do not include opening the HBA for this role though, so the security of who's allowed to trigger a manual failover is for you to solve.

We should certainly extend our documentation of those API entries: leaving the issue open so that we have a change to fix this.

**Comment by Wolfsrudel** [comment]
I'm fine with this. :)

**Comment by Wolfsrudel** [comment]
@DimCitus: is it possible to do a manual switchover for maintenance tasks? Fail over is the hard way, I guess.

**Comment by DimCitus** [comment]
Hi @Wolfsrudel, because we use Synchronous Replication, the failover is done in a way that prevents data loss. As a result it can be considered a switchover for maintenance, and that's why we don't have another API for that use case.
