### ISSUE TITLE
Wrong IP added to pg_hba.conf when multiple interfaces exist.

### ISSUE THREAD

**Issue by darkl0rd** [citusdata/pg_auto_failover#29]
In my specific case, the container has two interfaces. The IP from interface 1 was added to the pg_hba.conf - however connections seem to it from another container on the same network come from the secondary interface.

Oddly enough, the original "registration attempt" also is performed over the same network interface, so I'm confused as to why it decided to take the IP from the primary interface.

As an aside, there are many issues/inconveniences in the area of DNS resolution / pg_hba entries. For instance, given a setup of 3 containers: monitor, db1, db2: db1 and db2 register itself with monitor, db2 fails ot perform a pg_basebackup from db1 since db1 has 'db2' added in it's pg_hba.conf -- however somehow pg_basebackup tells me it can't resolve 'db1' to an IP whereas ping, dig, host have no problems in doing so.

**Comment by DimCitus** [comment]
Hi @darkl0rd ; thanks for your interest in pg_auto_failover!

We detail our approach to automatic network setup / discovery in the documentation at https://pg-auto-failover.readthedocs.io/en/latest/ref/reference.html#pg-auto-failover-monitor in the description of the `--nodename` command line switch.

The `--nodename` used to be mandatory and now can be discovered automatically to the right value in some cases, but not in every case. It seems your case is one where it does not work in a fully automated fashion yet: please consider using `--nodename`.

Also, about using DNS names, I'm copy/pasting from the pg_auto_failover README here:

> The provided --nodename is going to be used by pg_auto_failover to grant connection privileges in the Postgres HBA file. When using a hostname rather than an IP address, please make sure that reverse DNS is then working with the provided hostname, because that's how Postgres will then match any connection attempt with the HBA rules for granting connections, as described in Postgres documentation for the [pg_hba.conf](https://www.postgresql.org/docs/current/auth-pg-hba-conf.html) file, at the address field.

So you need to have properly working reverse DNS for the Postgres HBA to work with DNS names. If that's not the case for your setup, consider using IP addresses. 

It seems to me that in your case it might work to use `--nodename` when setting the monitor only. For the Postgres nodes, pg_auto_failover opens a connection to the monitor itself rather than to an external IP address, so that's why it usually just work there, once the monitor is properly setup.

**Comment by darkl0rd** [comment]
I have actually been using nodename. These names (db1 and db2) can reach each other just fine, it’s pg_basebackup that’s complaining it can’t resolve db2 to an IP.

I’m running this in Docker with service names set to db1 and db2 respectively.

**Comment by DimCitus** [comment]
Can you maybe paste a log output for us to understand the problem better? For now it does not sound like something I know how to fix, unfortunately...

**Comment by DimCitus** [comment]
Closing now for clean-up purposes. Please re-open this issue with more information if you still need help here.
