### ISSUE TITLE
certbot cert renewal doesn't work because of use of symlinks

### ISSUE THREAD

**Issue by edwardbattye** [citusdata/pg_auto_failover#344]
Hi I am trying to use certbot to prodivde the ssl certs for my postgres ssl, however I cannot get a renewed cert renewal to work. Certbot stores it's certs behind a simlink, however when I point my pg_auto ssl cert to the certbot directory /etc/letsencrypt/live/xxxxx/cert.pem pg_auto resolves the simlink to the actual location of the file and stores that in its config file, so /etc/letsencrypt/archive/xxx/cert121.pem for example. This means when you renew the certificate pg_auto is unaware as it is no longer looking at the symlink. I've tried manually editing the file but it gets auto replaced again.

postgres 10.13
ubuntu 18.04
pg_autoctl version 1.3

**Comment by DimCitus** [comment]
Hi @edwardbattye ; thanks for the bug report. What happens if you use the `pg_autoctl enable ssl` command after the symlink has been updated to the new certificate? I would think that we probe for the [realpath(3)](https://www.man7.org/linux/man-pages/man3/realpath.3.html) again and this time resolve to the new certificate, which should solve your issue maybe?

```
$ pg_autoctl enable ssl --help
pg_autoctl enable ssl: Enable SSL configuration on this node
usage: pg_autoctl enable ssl  [ --pgdata ] [ --json ] 

  --pgdata      path to data directory
  --ssl-self-signed setup network encryption using self signed certificates (does NOT protect against MITM)
  --ssl-mode        use that sslmode in connection strings
  --ssl-ca-file     set the Postgres ssl_ca_file to that file path
  --ssl-crl-file    set the Postgres ssl_crl_file to that file path
  --no-ssl          don't enable network encryption (NOT recommended, prefer --ssl-self-signed)
  --server-key      set the Postgres ssl_key_file to that file path
  --server-cert     set the Postgres ssl_cert_file to that file path
```

**Comment by edwardbattye** [comment]
Thanks @DimCitus that does help me solve that one.

**Comment by berlin-ab** [comment]
@DimCitus We're seeing a similar situation using cert-manager on Kubernetes. We were providing `pg_autoctl create postgres --monitor` with a connection string that does not include `sslrootcert`, instead relying on the `PGSSLROOTCERT` environment variable. When `pg_autoctl` stores `PGSSLROOTCERT` (something like /etc/sslconfig/ca.crt -> /etc/sslconfig/somewhere-else/ca.crt) it stores the full-path value instead of the literal value containing the symlink location.

**Comment by berlin-ab** [comment]
@DimCitus Is there a reason for storing the full path to the certificate instead of storing the symlink path? Would you be open to a pull request that stores the symlink path instead?

**Comment by DimCitus** [comment]
I @berlin-ab ; I think it boils down to re-using code that we use for PGDATA and other directories, where it's best that we deal with the actual real path rather than a symlink. I also think you're right saying that for the certificates we should probably use whatever PATH was given by the user, even if we might want to run some checks and process using the actual real path in some places (not sure really, we need to audit the code there I believe).

I would happily review and merge such a PR for sure! Do you want to get started on writing it?
