### ISSUE TITLE
Bug fix backpatching question

### ISSUE THREAD

**Issue by Eulerizeit** [citusdata/pg_auto_failover#430]
What is the policy on backpatching bug fixes?

For example if a bug were discovered in 1.3.1 that still existed in 1.4.x would the fix be backported into a 1.3.2 release?

**Comment by DimCitus** [comment]
Hi @Eulerizeit ; thanks for asking ! I don't think that we have such a policy at the moment. Thinking out loud: as a user upgrading from 1.3.1 to 1.3.2 or to 1.4.0/1.4.1 is going to be the same amount of efforts and the same procedure. Given that, we would have to know of a very strong reason to avoid the 1.4.x series in order to consider spending all the efforts to still maintain 1.3.x in parallel. What do you think?

**Comment by Eulerizeit** [comment]
I think that perfectly makes sense. 

This question came up as we were discussing how quickly we needed to upgrade to 1.4.x. 

If you could leave this open for a few days there might be some folks who have opinions and perspectives I haven't considered.

**Comment by DimCitus** [comment]
Closing for triaging, please feel free to re-open if needed.
