### ISSUE TITLE
document pg_hba and pg_ident requirements for cert authentication

### ISSUE THREAD

**Issue by s4ke** [citusdata/pg_auto_failover#431]
Hey,

When upgrading to 1.4, we found that 1.4 added some new requirements for pg_hba. 

On 1.3 this was enough:

```
hostssl autoctl autoctl_node 10.0.0.10/32   cert map=autoctl_node_remote
hostssl autoctl autoctl_node 10.0.0.11/32   cert map=autoctl_node_remote
hostssl autoctl autoctl_node 10.0.0.12/32   cert map=autoctl_node_remote
hostssl template1 autoctl_node 10.0.0.10/32   cert map=autoctl_node_remote
hostssl template1 autoctl_node 10.0.0.11/32   cert map=autoctl_node_remote
hostssl template1 autoctl_node 10.0.0.12/32   cert map=autoctl_node_remote
hostssl pg_auto_failover autoctl_node 10.0.0.10/32   cert map=autoctl_node_remote
hostssl pg_auto_failover autoctl_node 10.0.0.11/32   cert map=autoctl_node_remote
hostssl pg_auto_failover autoctl_node 10.0.0.12/32   cert map=autoctl_node_remote
hostssl replication pgautofailover_replicator 10.0.0.10/32   cert map=pgautofailover_replicator_remote
hostssl replication pgautofailover_replicator 10.0.0.11/32   cert map=pgautofailover_replicator_remote
hostssl replication pgautofailover_replicator 10.0.0.12/32   cert map=pgautofailover_replicator_remote
hostssl postgres pgautofailover_replicator 10.0.0.10/32   cert map=pgautofailover_replicator_remote
hostssl postgres pgautofailover_replicator 10.0.0.11/32   cert map=pgautofailover_replicator_remote
hostssl postgres pgautofailover_replicator 10.0.0.12/32   cert map=pgautofailover_replicator_remote
hostssl postgres pgautofailover_monitor 10.0.0.10/32   cert map=pgautofailover_monitor_remote
hostssl postgres pgautofailover_monitor 10.0.0.11/32   cert map=pgautofailover_monitor_remote
hostssl postgres pgautofailover_monitor 10.0.0.12/32   cert map=pgautofailover_monitor_remote
local all postgres    peer
local replication postgres    peer
local all all    peer
host all all 127.0.0.1/32   md5
host all all ::1/128   md5
```

with this pg_ident.conf:

```
hostssl autoctl autoctl_node 10.0.0.10/32   cert map=autoctl_node_remote
hostssl autoctl autoctl_node 10.0.0.11/32   cert map=autoctl_node_remote
hostssl autoctl autoctl_node 10.0.0.12/32   cert map=autoctl_node_remote
hostssl template1 autoctl_node 10.0.0.10/32   cert map=autoctl_node_remote
hostssl template1 autoctl_node 10.0.0.11/32   cert map=autoctl_node_remote
hostssl template1 autoctl_node 10.0.0.12/32   cert map=autoctl_node_remote
hostssl pg_auto_failover autoctl_node 10.0.0.10/32   cert map=autoctl_node_remote
hostssl pg_auto_failover autoctl_node 10.0.0.11/32   cert map=autoctl_node_remote
hostssl pg_auto_failover autoctl_node 10.0.0.12/32   cert map=autoctl_node_remote
hostssl replication pgautofailover_replicator 10.0.0.10/32   cert map=pgautofailover_replicator_remote
hostssl replication pgautofailover_replicator 10.0.0.11/32   cert map=pgautofailover_replicator_remote
hostssl replication pgautofailover_replicator 10.0.0.12/32   cert map=pgautofailover_replicator_remote
hostssl postgres pgautofailover_replicator 10.0.0.10/32   cert map=pgautofailover_replicator_remote
hostssl postgres pgautofailover_replicator 10.0.0.11/32   cert map=pgautofailover_replicator_remote
hostssl postgres pgautofailover_replicator 10.0.0.12/32   cert map=pgautofailover_replicator_remote
hostssl postgres pgautofailover_monitor 10.0.0.10/32   cert map=pgautofailover_monitor_remote
hostssl postgres pgautofailover_monitor 10.0.0.11/32   cert map=pgautofailover_monitor_remote
hostssl postgres pgautofailover_monitor 10.0.0.12/32   cert map=pgautofailover_monitor_remote
local all postgres    peer
local replication postgres    peer
local all all    peer
host all all 127.0.0.1/32   md5
host all all ::1/128   md5
```

Our ssl certs have the IP of the host as the CN.

On a 3 node setup I had to add the following lines for the cluster to work properly:

```
hostssl postgres pgautofailover_replicator 10.0.0.10/32   cert map=pgautofailover_replicator_remote
hostssl postgres pgautofailover_replicator 10.0.0.11/32   cert map=pgautofailover_replicator_remote
hostssl postgres pgautofailover_replicator 10.0.0.12/32   cert map=pgautofailover_replicator_remote
```

Apparently the pgautofailover_replicator user now needs access to the postgres db as well.

Was this documented somewhere? I found these things out by trial and error, but is there a central place for the users that are used for which operation?

**Comment by DimCitus** [comment]
Hi @s4ke ; the current documentation about HBA and security and certificates is found at https://pg-auto-failover.readthedocs.io/en/latest/security.html and I realise it does not cover the whole list of needed authorisations. That's something that we should probably fix.

The reason why those new lines are needed is due to the new function `upstream_has_replication_slot` defined at https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/primary_standby.c#L369 ; we call that function at two places in the code, both times before we do a `pg_basebackup`. This helps with the following two problems:

  - we now allow multiple standby nodes to register concurrently, and we need to make sure that the primary has created the HBA entry and the replication slot for the local standby node before `pg_autoctl` continue with the initialisation ; and so some the responsibility that used to be on the monitor side when assigning the new FSM state now has shifted to the `pg_autoctl` client side which connects to the primary and check if the replication slot has been created already ;

 - there is a bug in Postgres `pg_basebackup` where it will happily download the whole of PGDATA even when it knows from the start that the replication slot does not exists, and then the command fails after the whole copy. With non-trivial PGDATA sizes, we really want to avoid that situation and we go out of our way to prevent it.

**Comment by DimCitus** [comment]
I believe the current documentation at https://pg-auto-failover.readthedocs.io/en/master/security.html# is a good answer to this issue. Please re-open if you feel like we need more details, and make sure to share what you think is missing then.
