### ISSUE TITLE
Why keeper connects to monitor and disconnects?

### ISSUE THREAD

**Issue by RekGRpth** [citusdata/pg_auto_failover#436]
Why not keep connection to monitor?

**Comment by DimCitus** [comment]
At the moment we keep a connection alive when doing FSM changes (a failover for instance). When nothing is happening we reconnect every second. That's best with how Postgres works, long running connections are to be avoided in production, because they tend to prevent proper auto vacuum activity.

**Comment by RekGRpth** [comment]
> That's best with how Postgres works, long running connections are to be avoided in production, because they tend to prevent proper auto vacuum activity.

I think long running connections do not tend to prevent proper auto vacuum activity if they use short transactions and do not leave opened transactions (idle in transaction state).

How about to keep connections one hour or so on and then close and open again?

**Comment by DimCitus** [comment]
It's a good point overall. I'm not sure of the advantages of keeping the connection for a long time, though we could experiment with the idea. Re-opening then. Do you want to contribute the feature, it sounds like a nice self-contained patch and would be a good first issue?

**Comment by JelteF** [comment]
@RekGRpth what's the advantage you hope to gain by keeping the connection open and reusing it? In normal applications it's usually because connecting requires a couple of roundtrips and you want to avoid those to keep query latency down. I don't think this matters much for connecting to the monitor though. 

I see you suggest using prepared statements, but this will only save in query planning+parsing time. Since the monitor should not be bottlenecked on CPU at all, I don't understand the advantage of using prepared statements for keeper queries to the monitor.

One nice thing from reconnecting over and over is that we can easily depend on connect timeouts being triggered. Detecting that an existing connection died is usually a bit harder than detecting a connection never opens (not super hard though). If we go with long-lived connections, we have to make sure that all the ways in which a network can fail keep behaving in the expected way.
