### ISSUE TITLE
How create formation before keeper node creation?

### ISSUE THREAD

**Issue by RekGRpth** [citusdata/pg_auto_failover#437]
How create formation before keeper node creation?
In node host, not on monitor host!
May You add `--monitor` option to `pg_autoctl create formation` command?

**Comment by RekGRpth** [comment]
Also may add `--monitor` option to other commands, that does not require config existing

**Comment by RekGRpth** [comment]
or may be command `pg_autoctl create postgres` will create formation if not exists?

**Comment by DimCitus** [comment]
It is possible to `pg_autoctl create formation` on the monitor node, and then to `pg_autoctl create postgres --formation ... ...` on the Postgres node. I think your idea of adding `--monior` support in the `pg_autoctl create formation` command makes sense, so that we could do that from the Postgres node too. Unfortunately, it looks like we are running out of time for 1.4.1 and we will address that in 1.4.2, later.

**Comment by RekGRpth** [comment]
> I think your idea of adding --monitor support in the pg_autoctl create formation command makes sense, so that we could do that from the Postgres node too

Yes, but why not create formation if not exists via command `pg_autoctl create postgres` because it use `--monitor` option
