### ISSUE TITLE
Doubling all command line options by environment variables

### ISSUE THREAD

**Issue by RekGRpth** [citusdata/pg_auto_failover#438]
How about to double all command line options by environment variables? Like `--pgdata` and `PGDATA`

It will be very useful for using in docker.

**Comment by DimCitus** [comment]
Nope.

There is a cost to environment variables, it's called I think action-at-a-distance. Also it makes things harder to debug. We should limit how many environment variables are impacting our implementation and stick to the minimum. We use PGDATA because Postgres tooling uses PGDATA. We try to be compatible with Postgres and use the same tooling, but that's about it. We then have our own PG_AUTOCTL_DEBUG switch to open the developer toolbox.
