### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by mgonzaga1990** [citusdata/pg_auto_failover#453]
This is tool is excellent. But would like to check if this is available in non x86_64 arch? like arm64 for raspberry pi?

**Comment by DimCitus** [comment]
Hi @mgonzaga1990 ; thanks for the kind words!

It should be, in theory, that if you can compile Postgres you can compile pg_auto_failover. Same dependencies, written in the same language (C), etc. What happens when you try to compile from sources?

When using debian you could use the following commands to compile pg_auto_failover for Postgres 11 with the correct dependencies and all:

```
$ sudo apt-get build-dep -q -y postgresql-11
$ sudo apt-get install -q -y postgresql-server-dev-all libkrb5-dev
$ make PG_CONFIG=/usr/lib/postgresql/11/bin/pg_config -C pg_auto_failover -s clean all
$ sudo make PG_CONFIG=/usr/lib/postgresql/11/bin/pg_config BINDIR=/usr/local/bin -C pg_auto_failover install
```

I don't think we have debian integration in apt.postgresql.org yet, and when we do we might have ARM64 and other architectures covered from there.

**Comment by brsc2909** [comment]
I've  just tested and can confirm this works on the 32bit armv71 raspberry pi 3, running Raspbian Buster
