### ISSUE TITLE
Are pg_autoctl events only limited to state transitions?

### ISSUE THREAD

**Issue by rheaton** [citusdata/pg_auto_failover#463]
Hello Dimitri,

Currently, events are limited to state transitions, but we were thinking that requesting to drop a node should be added to events as well. The drop isn't implemented as a state-transition, so what do you think?

Thanks,
Rachel & Jacob
@jchampio

**Comment by soumyadeep2007** [comment]
I think `stop` and `run` also qualify as events semantically

**Comment by DimCitus** [comment]
Hi folks,

Yes we could and probably should add drop as an event, good point. 

I'm not sure about stop and run, because it would convey the impression that we know more about the situation than we actually do. For instance, network splits might be understood as a stop. Or if we add am explicit stop message in our protocol, what about `kill -9` or other exit code paths where we don't/can't call the stop message, and the monitor is in the blind?

**Comment by DimCitus** [comment]
In https://github.com/citusdata/pg_auto_failover/pull/397 we added a LogAndNotifyMessage call when a node is removed. In a recent bug fix I added a LogAndNotifyMessage call when a new node is registered, the PR here is not opened yet, I will track it here when it is.

Given the two improvements we will then be able to close that Issue.

**Comment by DimCitus** [comment]
See https://github.com/citusdata/pg_auto_failover/commit/737a6b9284b177a1904e100650610946f5e5555f
