### ISSUE TITLE
Installation issues on centos 8

### ISSUE THREAD

**Issue by shmuelse** [citusdata/pg_auto_failover#477]
I installed the package according to the instructions on the blog:  [https://blog.dbi-services.com/pg_auto_failover-setup-and-installation/](blog.dbi)
When I get to the make stage in the folder:
`  / home / postgres / pg_auto_failover /`
I get the following message:

```
make -C src / monitor / all
make [1]: Entering directory '/ home / postgres / pg_auto_failover / src / monitor'
make [1]: pg_config: Command not found
make [1]: pg_config: Command not found
make [1]: *** No rule to make target 'all'. Stop.
make [1]: Leaving directory '/ home / postgres / pg_auto_failover / src / monitor'
make: *** [Makefile: 43: monitor] Error 2
```

Is it possible that someone has an idea to solve the problem?
I use centos 8 with postgresql-12

```
pg_autoctl version 1.4
pg_autoctl extension version 1.4
compiled with PostgreSQL 12.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5), 64-bit
compatible with Postgres 10, 11, 12, and 13
```

**Comment by DimCitus** [comment]
Hi @shmuelse ; thanks for reporting an issue and using pg_auto_failover. Is there any particular reason why you would want to use the software from sources rather than a packaged version? See https://packagecloud.io/citusdata/community/install#bash-rpm for using our packages for CentOS directly.

Other than that you need to install the build dependencies when you want to compile pg_auto_failover from sources, and that includes Postgres `pg_config` tool, which comes with the development packages for Postgres.
