### ISSUE TITLE
Question: Why are the WAL defaults set so large?

### ISSUE THREAD

**Issue by rheaton** [citusdata/pg_auto_failover#517]
Hello!

We were wondering how the defaults set in [primary_standby.c](https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/primary_standby.c#L69) 

Since `wal_keep_segments` is set to 512 we need at least 8GB+ to run pg_auto_failover. Do we believe these are the minimum requirements for pg_auto_failover, or was this tuning done for a particular use-case. 

There are other bits of tuning in that file that may be useful for us to know about, if you have the context. 

Thank you,
Rachel

cc @jchampio

**Comment by menicosia** [comment]
+1 we are really interested in understanding the reasoning behind the current defaults, rather than blindly stomp over them without understanding the implications of our changes.

We're considering making changes based on the need to have "micro instances" in Dev & Test which reflect what production will eventually look like. We believe that dialing this number down in Dev & Test reduces the disk requirements, but won't significantly affect app performance when we deploy to prod with larger configuration.

**Comment by DimCitus** [comment]
Hi @rheaton, @jchampio, @menicosia  ; that's a good question to ask.

So when using Postgres streaming replication without replication slots, the only stop-gap you have for things to “just work” on the replica side is then `wak_keep_segments`. Keeping 512 of them only consumes 8GB of disk space, and is a simple and efficient way to escape situations where you would otherwise have to use `pg_basebackup` instead of `pg_rewind`.

After this default setting has been set to 512 in pg_auto_failover, we finished implemented support for replication slots on every node, so it might be argued that we don't need it anymore. We still support Postgres 10 though, where it is still needed (because of the lack of `pg_replication_slot_advance()` function there).

I think we could accept a patch to review that decision, where we check that we can trust replication slots in every case and stop having a second-level stop-gap solution in place.

Also for your own environments, that risk situation is yours to analyse and the best trade-off is of course yours to find. All we can do in pg_auto_failover itself is try to come up with meaningful defaults.

**Comment by DimCitus** [comment]
Closing for triaging purposes, feel free to re-open with more questions/informations of course.
