### ISSUE TITLE
Node_b always on wait_standby

### ISSUE THREAD

**Issue by Doumham-Armah** [citusdata/pg_auto_failover#542]
I am trying to test pg_autofailover on multiple hosts.
setting up the monitor on the 1st host:
```
pg_autoctl create monitor   \
  --pgdata ./monitor     \
  --pgport 5000          \
  --nodename `hostname --fqdn`
```

setting up the _node_a_ on the 2nd host:
```
pg_autoctl create postgres     \
  --pgdata ./node_a \
  --pgport 5001             \
  --nodename 127.0.0.1      \
  --pgctl `which pg_ctl` \
  --monitor postgres://autoctl_node@<Public IPv4 DNS of 1st host>:5000/pg_auto_failover

pg_autoctl run --pgdata ./node_a

```

However when setting up _node_b_ on the 3rd host like the follwoing:
```
pg_autoctl create postgres     \
  --pgdata ./node_b \
  --pgport 5002             \
  --nodename 127.0.0.1      \
  --pgctl `which pg_ctl` \
  --monitor postgres://autoctl_node@<Public IPv4 DNS of 1st host>:5000/pg_auto_failover

```
I get the following ERROR:
```
ERROR pg_basebackup: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5001?
```
I am pretty new to this and would really appreciate any suggestions/insights.

**Comment by DimCitus** [comment]
Hi @Doumham-Armah ; thanks for using pg_auto_failover. Please specify which version you're using when opening issues.

In pg_auto_failover 1.4.0 and following, the `--nodename` is a nickname you may give to your Postgres nodes, and will default to `node%d` when you don't specify it. The `--hostname` argument is the IP address that other nodes will use to connect to the node being registered, and that's what should not be `127.0.0.1` but is in your case. Because I can't see any use of `--hostname` in your commands, I suppose the computed default is being used, and our best guess is wrong in your case.

Before version 1.4.0 we only had support for the `hostname` notion and would use `--nodename` to register the IP address to use to connect to a node being registered. When using `--nodename 127.0.0.1` as you're doing, you are saying that other nodes and the monitor can connect to your node using that IP address, and later it appears that it's not the case.

**Comment by Doumham-Armah** [comment]
Terribly sorry.
I am using pg_auto_failover version 1.0, Postgres 11, and CentOS. I am following this [tutorial](https://cloudblogs.microsoft.com/opensource/2019/05/06/introducing-pg_auto_failover-postgresql-open-source-extension-automated-failover-high-availability/) since I am having trouble following yours as I cannot find the build-dependencies specified for centos 7.
