### ISSUE TITLE
Which configuration does the pg node actually use?

### ISSUE THREAD

**Issue by kevinelliott** [citusdata/pg_auto_failover#593]
I have several configuration files from `pg_auto_failover` provisioned nodes.

```
-rw------- 1 postgres postgres    158 Jan 11 17:51 postgresql.auto.conf
-rw-r--r-- 1 postgres postgres   1085 Jan 10 00:07 postgresql-auto-failover.conf
-rw-r--r-- 1 postgres postgres      0 Jan 11 17:51 postgresql-auto-failover-standby.conf
-rw------- 1 postgres postgres  28285 Jan 10 00:01 postgresql.conf
-rw------- 1 postgres postgres     79 Jan 10 00:07 postmaster.opts
-rw------- 1 postgres postgres     89 Jan 11 17:51 postmaster.pid
```

The values in `postgresql.conf` are fairly default and do not meet the needs of my server load. The values in `postgresql-auto-failover.conf` seem to have auto-calculated some values that are within spec. I'm not clear which one takes precedence, and whether or not I can manually adjust values in either of them.

I've looked in documentation, looked in the process list, and otherwise try to dig around on the system and try to get some hint on which is being used, but sadly have made no progress there.

Can you please help clarify some of this?

**Comment by DimCitus** [comment]
Hi @kevinelliott,

In pg_auto_failover we add an `include 'postgresql-auto-failover.conf` directive to the main `postgresql.conf` file, at the very beginning of the file. You can edit your `postgresql.conf` file any way you need, or use the `ALTER SYSTEM` command, or use the `ALTER DATABASE ... SET` or `ALTER ROLE ... SET` commands as usual.

Just make sure that our `include` line is always in place first thing in the file, so that the values that pg_auto_failover need are set correctly, and so that your own choices then are allowed to override pg_auto_failover defaults when you need to.

To audit the provenance of configuration settings, use the `pg_settings` view as usual:

```
demo=# select name, setting, sourcefile, sourceline from pg_settings where sourcefile is not null limit 10;
              name               |      setting       |                                 sourcefile                                  | sourceline 
---------------------------------+--------------------+-----------------------------------------------------------------------------+------------
 autovacuum_analyze_scale_factor | 0.02               | /Users/dim/dev/MS/pg_auto_failover/tmux/node1/postgresql-auto-failover.conf |         34
 autovacuum_max_workers          | 3                  | /Users/dim/dev/MS/pg_auto_failover/tmux/node1/postgresql-auto-failover.conf |         32
 autovacuum_vacuum_scale_factor  | 0.08               | /Users/dim/dev/MS/pg_auto_failover/tmux/node1/postgresql-auto-failover.conf |         33
 DateStyle                       | ISO, MDY           | /Users/dim/dev/MS/pg_auto_failover/tmux/node1/postgresql.conf               |        650
 default_text_search_config      | pg_catalog.english | /Users/dim/dev/MS/pg_auto_failover/tmux/node1/postgresql.conf               |        673
 dynamic_shared_memory_type      | posix              | /Users/dim/dev/MS/pg_auto_failover/tmux/node1/postgresql.conf               |        141
 effective_cache_size            | 1572864            | /Users/dim/dev/MS/pg_auto_failover/tmux/node1/postgresql-auto-failover.conf |         31
 hot_standby                     | on                 | /Users/dim/dev/MS/pg_auto_failover/tmux/node1/postgresql-auto-failover.conf |         11
 hot_standby_feedback            | on                 | /Users/dim/dev/MS/pg_auto_failover/tmux/node1/postgresql-auto-failover.conf |         10
 lc_messages                     | en_US.UTF-8        | /Users/dim/dev/MS/pg_auto_failover/tmux/node1/postgresql.conf               |        666
(10 rows)
```

Closing this issue in the hope that your question is fully answered. If not, feel free to ask more questions and even re-open this issue.
