### ISSUE TITLE
Question: Is there a way to have a synchronous external cosumer?

### ISSUE THREAD

**Issue by giner** [citusdata/pg_auto_failover#603]
In the default setup pg_auto_failover configures synchronous_standby_names as "ANY N of M" which makes it impossible to attach an external to the cluster synchronous consumer. Is there a way to tell the monitor about an external consumer and make it configure synchronous_standby_names as "FIRST N of M" where that consumer is in the first N nodes (if we want it to be synchronous). Would this be a potential feature in future releases if not possible now?

**Comment by AnshumanRohella** [comment]
+1 following.

**Comment by DimCitus** [comment]
Hi @giner ; I'm not sure I understand your question completely. It seems on a quick read that the answer is to use `replication-quorum false` on this “external” node, as documented at https://pg-auto-failover.readthedocs.io/en/latest/architecture-multi-standby.html#replication-quorum. Is that the case?

**Comment by giner** [comment]
Sorry, I haven't mentioned that the "external" node cannot be joined to the cluster in our case as it is not PostgreSQL node but Barman which works as streaming "client".

**Comment by DimCitus** [comment]
Well then it seems to me that this should be external to pg_auto_failover entirely. I suppose that you would like the barman node to be part of the synchronous_standby_names list, but at the moment there is no way to make that happen with pg_auto_failover. We are working on Disaster Recovery support, and I hope we can achieve a design that would allow working better with barman here. 

Closing this issue because there is no practical way to move forward until we have Disaster Recovery support added to the project.
