### ISSUE TITLE
Was the Project Documentation moved?

### ISSUE THREAD

**Issue by sacrophyte** [citusdata/pg_auto_failover#640]
It seems like all the old links to "latest" are broken:
https://pg-auto-failover.readthedocs.io/en/latest/

However, the "master" documentation is still available:
https://pg-auto-failover.readthedocs.io/en/master/

**Comment by DimCitus** [comment]
Hi @sacrophyte ; I changed the settings on what to produce on readthedocs admin panel, so that we maintain publication of some release tags (currently v1.3.2 and v1.4.2) and also the current latest from the source tree. I though that “latest” wasn't clear enough for casual readers so I removed it, and kept only “master”, the name of the default git branch.

**Comment by sacrophyte** [comment]
Ok, that makes sense. You might want to update all the links so they no longer point to "latest". :)
