### ISSUE TITLE
Docker: Upgrading pg_auto_failover monitor causes postgres nodes to terminate and cluster downtime

### ISSUE THREAD

**Issue by jnehlmeier** [citusdata/pg_auto_failover#749]
Hi,

we are planning to use pg_auto_failover with Docker and the upgrade process introduced in 1.4 sounds nice but doesn't really work well with Docker. The reason is that the pg_autoctl process terminates and tries to restart as soon as it detects a version mismatch with the (updated) monitor. This causes the postgres cluster to fully terminate until the docker image of postgres nodes has also been updated and restarted.

Are there any recommendations how to update pg_auto_failover with docker without downtime? Even if pg_autoctl would get an option to not restart itself as soon as it detects a version mismatch, switchover can probably not be done since nodes can not be coordinated anymore.

I tink in an ideal world it should work similar to

1. Monitor will be upgraded from version A to B. Monitor can still speak to postgres nodes using the old protocol version A, but it also supports now the new protocol version B.
2. Update docker image of postgres secondaries so they now also speak protocol version B
3. Do a switchover (coordinating using the correct protocol version A or B, depending on the node)
4. Update docker image of old postgres primary so it speaks protocol version B.

**Comment by JelteF** [comment]
Hmm, this is indeed a scenario we didn't really think about when designing the upgrade story. The flow you propose does sound nice, but there's quite a lot of edge cases with running mixed versions that are nice not to have to support (e.g. additions/changes to the FSM). 

A flow that might work for you is the following that introduces an "upgrade container" in a way like this:
1. Have nodes on version A
2. Create docker container with version A installed, but with the package for version B downloaded as a `deb`/`rpm`
3. Replace secondary containers with these upgrade containers
4. Do a switchover
5. Replace primary container with this upgrade container
6. Run this in all docker containers `exec dpkg -i pgautofailover-vB.deb`. binaries are swapped B, but running version is still A
7. Upgrade the monitor to the container with only version B (no need for the "upgrade container" here)
8. Inplace upgrade to B will happen on the other nodes now, since the binaries have been swapped
9. Upgrade the secondaries to a container with only version B
10. Do a switchover
11. Upgrade the old primary to a container with only version B

**Comment by jnehlmeier** [comment]
This could work. We will try it once 1.6.x packages are available.

However this isn't really scaleable if you have multiple clusters. So I hope you will think about a more cloud native upgrade solution that does not need that much manual intervention.

I can see that changing available states in FSM is problematic so maybe a compromise would be:
1. Increase Major version if FSM states have been modified. Manual intervention needed during upgrade. Hopefully this only happens rarely once FSM has been settled. 
2. For feature updates (minor version) and patch updates (patch version) pg_auto_failover speaks the current version protocol as well as the previous version so that automated updates can be done.

**Comment by DimCitus** [comment]
I have coded the idea that we don't exit until ready, which in the case of a docker container means we continue running Postgres locally after the monitor's upgrade. You still have to restart the docker container with the new version of course, but it will refrain from the exit and thus avoid the supervisor retry policy problem you currently have.

To support several versions for the FSM at once in a single binary (both at the monitor and the keeper) would increase our software complexity a lot. It's attractive to have something that “just works” out of the box, but guaranteeing that when you could have multiple versions of the protocol in flight at the same time is going to be tricky, maybe to the detriment of the robustness of the program. I will continue thinking about it to see how to tame this complexity. If we find a good way to make it happen, that'd be good.

**Comment by DimCitus** [comment]
I believe #771 improves the matter in a way that allows closing this issue. Please re-open with details if we still need to work on the topic.
