### ISSUE TITLE
Failover results in stale/stuck replication slots

### ISSUE THREAD

**Issue by jchampio** [citusdata/pg_auto_failover#814]
_I believe this is a duplicate of #662, which was closed not too long ago. FYI @porsager_

We've run into a production instance that was complaining about `WARNING:  oldest xmin is far in the past`, a few days after a failover occurred. We discovered that an inactive replication slot on the _secondary_ was pinning an old xmin value. (Dropping and recreating the _primary's_ replication slots did not help, which is potentially why that workaround did not help #662?) Dropping the secondary's slots released the xmin.

We were able to reproduce this situation with the following steps (though we don't know for sure that this is what happened to the production cluster):
1. Set up a two-node instance. Add a table with some data. At this point, the primary should have an active replication slot with a recent xmin, and the secondary should have a blank, inactive slot.
2. Kill the primary, and wait for the demotion timeout and for the secondary to be promoted to primary.
3. Bring the demoted node back online and wait for it to rewind.
4. Connect to the new secondary and note that a stale, inactive replication slot is still holding onto that old xmin.
5. Connect to the primary and commit some transactions. Note that the primary's replication slot never advances its xmin (since the secondary's slot is still pinning it).

Performing a manual switchover also triggers this issue. But if I manually kill the primary and bring it back up _before_ the demotion timeout, I don't see this problem, even after the failover.

We've reproduced against Postgres 13.2, with pg_auto_failover versions 1.5.2 and 1.6.2.

**Comment by porsager** [comment]
Hey @jchampio .

I'm glad you've come so far debugging this. I've got the same issue happening currently, so I'll give it a try deleting the secondarys replication slot for a temporary fix.

I'll get back once I know if that helped.

**Comment by porsager** [comment]
That instantly solved the issue. Thanks a lot for that insight! At least now I have a way to fix it once it happens.

**Comment by porsager** [comment]
@DimCitus I'm thinking this issue is related to pg_auto_failover, in that perhaps it doesn't clean up these slots on secondaries in case of a failover?

**Comment by DimCitus** [comment]
> @DimCitus I'm thinking this issue is related to pg_auto_failover, in that perhaps it doesn't clean up these slots on secondaries in case of a failover?

Hi @porsager, hi @jchampio. Thanks for continuing the investigation. And yes I agree this sounds like a pg_auto_failover bug with the management of the replication slots on a secondary node. I still need to reproduce locally and investigate, but it looks like we would fail to call `pg_replication_slot_advance()` for some reasons, or maybe that due to the rewind this call is failing, but in a way that our query fails to realise it's failing?

Could you guys invest some debugging time into the situation and maybe have some DEBUG or TRACE level logs of the replication slot management on the former-primary node, and maybe run the same SQL query manually to see if the slot management call is successful?

**Comment by DimCitus** [comment]
Hi,

So I have started to look into this area. To create a table and generate SQL traffic with INSERTs I have used the pg_auto_failover demo application:

```
$ pg_autoctl do demo run --clients 30 --duration 300 --first-failover 30 --failover-freq 300
```

Then I had a look at the result of the following query and I see that the replication slots xmin stops making any progress after a failover. What's interesting too is that before the failover, on the standby, the xmin is NULL and is kept that way. So it seems that `pg_replication_slot_advance()` is not taking care of the xmin, which means that after a failover, when the old primary is assigned `demoted`, we should probably delete any local replication slot.

``` sql
select slot_name, active, xmin, restart_lsn from pg_replication_slots;
```

**Comment by porsager** [comment]
Great to hear you can replicate this @DimCitus .

I really appreciate you've had time to look into this, and apologies for not getting back to you on debugging, I unfortunately haven't had time to look into it yet, but let me know if there's something else and I'll see what I can do.

**Comment by DimCitus** [comment]
Hey @porsager and @jchampio could you have a look and maybe even a run with the PR attached? In my testing this fixes the bug you reported, in that the xmin gets back to being NULL, rather than stuck at an old value after a failover. I also want to note that the `restart_lsn` of the replication slot was properly maintained, so I suppose we can file this one as a Postgres bug in `pg_replication_slot_advance` when it has to deal with an inactive slot that used to be active.

**Comment by jchampio** [comment]
>could you have a look and maybe even a run with the PR attached? In my testing this fixes the bug you reported, in that the xmin gets back to being NULL, rather than stuck at an old value after a failover.

Will do!

> I also want to note that the restart_lsn of the replication slot was properly maintained, so I suppose we can file this one as a Postgres bug in pg_replication_slot_advance when it has to deal with an inactive slot that used to be active.

I don't think `pg_replication_slot_advance` is documented to do anything with the global xmin, but I agree that having some way to manually manage a hot standby's slot seems like it would be a desirable feature.

**Comment by jchampio** [comment]
@DimCitus With this patch, both the demotion-timeout and switchover cases are fixed on my machine.
