### ISSUE TITLE
feature request custom log file location

### ISSUE THREAD

**Issue by Tiago-DBA** [citusdata/pg_auto_failover#834]
Salut Dimitri,

some admin and security teams can be very upset and refuse usage of journalctl for logs.

Aim of ticket is to provide an option for allocate pg_autoctl logs  on a custom location (directory + file) .

I understand one of pg_autofailover goals is to be easy to configure. 

But here we have some kind of security arguments...

Currently for me it's a kind of show stopper to go to production with pg_autoctl

Merci

Tiago

**Comment by redbaron** [comment]
related to https://github.com/citusdata/pg_auto_failover/issues/389

**Comment by DimCitus** [comment]
Hi @Tiago-DBA and @redbaron ; as you're already using systemd it seems to me that this is a systemd question. Specifically, have a look at the [StandardOutput=](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardOutput=) option docs including the `file:` and `append:` support, and tweak your systemd setup according to your needs.

Remember that the `pg_autoctl show systemd` command outputs a template to help users get started. I strongly believe it's part of the local admin job to review and adapt this template to what they actually require for their production setup, and as a result I don't think we should be able to take care of every possible case in pg_autoctl itself.

It used to be that every single service (daemon) on a Unix system had to implement all-over again all the system integration shenanigans, including log file rotation and syslog compatibility and all the jazz. It seems to me that nowadays a service is expected to output to stdout and be done with it, then another component of the OS has the job of handling the logs. In your case, because you're using systemd, then that job falls onto systemd, I would argue.

**Comment by Tiago-DBA** [comment]
Thanks Dimitri, it is very clear pg_autoctl -d provides log to stdout, so we can  customize using the service system tool in charge of launching pg_autoctl. So feature is already provided.
