### ISSUE TITLE
HOWTO use pg_auto_failover in existing PG cluster

### ISSUE THREAD

**Issue by wiwwo** [citusdata/pg_auto_failover#903]
It would be great to have a tutorial how to use `pg_auto_failover` on existing PG cluster (without any HA solution).
The instructions here
https://github.com/citusdata/pg_auto_failover#installing-pg_auto_failover-on-top-of-an-existing-postgres-setup
simply do not work, and are IMHO "yeah, whatever" :-)

**Comment by DimCitus** [comment]
The README is just an intro, not the actual documentation of the product. That's why you have this feeling about how light the instructions are. Consider reading the docs at https://pg-auto-failover.readthedocs.io/en/master/ref/pg_autoctl_create_postgres.html#description and then if still needed open this issue again with more questions. Would be best if you tried it first and then reported surprises or faults.
