### ISSUE TITLE
bug on pid directory

### ISSUE THREAD

**Issue by Tiago-DBA** [citusdata/pg_auto_failover#908]
Hi Dimitri,

pg_autoctl creates pid files on directory /tmp/pg_autoctl/mylinuxuser
this user should be on linux group postgres

first user is pgappli1 (group postgres)
second user is pgappli2 (group postgres)

issue:
mkdir: cannot create directory ‘/tmp/pg_autoctl/pgappli2’: Permission denied

because first user (e.g. pgappli1) creates : drwxr-xr-x 1 pgappli1 postgres 32 Jun  1 16:34 pg_autoctl

please during creation switch /tmp/pg_autoctl  to 775 rather than 755

**Comment by DimCitus** [comment]
Hi @Tiago-DBA ;

Again, while we could certainly change the privileges, I think there might be a better approach. I just checked and unfortunately that's not documented, which certainly explains why you missed it, that's on me...

In pg_autoctl we use the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) to determine where to store and read our files. See for instance the following source:
 https://github.com/citusdata/pg_auto_failover/blob/efcfb73e4a2be4a315a74cf2e1b583cafc85fe0e/src/bin/pg_autoctl/config.c#L248

And then

https://github.com/citusdata/pg_auto_failover/blob/efcfb73e4a2be4a315a74cf2e1b583cafc85fe0e/src/bin/pg_autoctl/config.c#L68

Given that, you can change XDG_RUNTIME_DIR to point to where you want to have the pidfile and other temporary files created for your instance, and maintain different values for different users. 

I'm going to leave that issue opened with the following items to solve:
  - [ ] document the environment variables in the manual pages, including XDG things
  - [ ] Use TMPDIR instead of XDG_RUNTIME_DIR, I think that's a better fit, as I recently learned in https://github.com/dimitri/pgcopydb/pull/26
